title: Australian Bioimage Analysts' Society
email: "-"
description: >
  The Australian Bioimage Analysts' Society is dedicated to supporting and connecting bioimage analysts across Australia.
baseurl: ""
url: "https://ausbias.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav:
  - title: "About"
    url: "/about/"
  - title: "Events"
    url: "/events/"
  - title: "Resources"
    url: "/resources/"
  - title: "Contact"
    url: "/contact/"

# Disable posts (remove blog-related settings)
collections:
  posts:
    output: false

# Pages
pages:
  - title: "About"
    file: "about.md"
  - title: "Events"
    file: "events.md"
  - title: "Resources"
    file: "resources.md"
  - title: "Contact"
    file: "contact.md"