title: Australian Bioimage Analysts' Society
email: "contact@bioimageanalysts.org"
description: >
  The Australian Bioimage Analysts' Society is dedicated to supporting and connecting bioimage analysts across Australia.
baseurl: ""
url: "https://yourusername.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav:
  - title: "About"
    url: "/about/"
  - title: "Events"
    url: "/events/"
  - title: "Resources"
    url: "/resources/"
  - title: "Community"
    url: "/community/"
  - title: "Contact"
    url: "/contact/"
