title: Australian Bioimage Analysts' Society
email: "https://groups.google.com/g/ausbias"
description: >
  The Australian Bioimage Analysts' Society is dedicated to supporting and connecting bioimage analysts across Australia.
baseurl: ""
url: "https://ausbias.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav:
  - title: "About"
    url: "/about/"
  - title: "Events"
    url: "/events/"
  - title: "Resources"
    url: "/resources/"
  - title: "Community"
    url: "/community/"
  - title: "Contact"
    url: "/contact/"

# Disable posts (remove blog-related settings)
collections:
  posts:
    output: false