title: Australian Bioimage Analysts' Society
email: "-"
description: >
  The Australian Bioimage Analysts' Society is dedicated to supporting and connecting bioimage analysts across Australia.
baseurl: ""
url: "https://drlachie.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav:
  - title: "About"
    url: "/about/"
  - title: "Events"
    url: "/events/"
  - title: "Resources"
    url: "/resources/"
  - title: "Contact"
    url: "/contact/"
  - title: "Blog"
    url: "/blog/"

permalink: /blog/:year/:month/:day/:title/

# Disable posts (remove blog-related settings)
#collections:
#  posts:
#    output: True

# Pages
pages:
  - title: "About"
    file: "about.md"
  - title: "Events"
    file: "events.md"
  - title: "Resources"
    file: "resources.md"
  - title: "Contact"
    file: "contact.md"
  - title: "Blog"
    file: "blog.md"


sass:
  style: compressed

collections:
  members:
    output: true
    permalink: /members/:name/